// AUTO-GENERATED by scripts/sync-lua-agents.mjs — do NOT edit manually.
// Run `node scripts/sync-lua-agents.mjs` or `npm run agents:sync` to regenerate.
// Source files: src/server/lua-agents/agents/*.lua

export const STUB = `
-- Stub agent — returns ok with no suggestions until a real implementation is added.
function run(ctx)
  mh_log("stub agent run", ctx.agent_id)
  return { status = "ok", suggestions = {}, tasks = {}, notifications = {} }
end
`;

export const BOOKING_SCOUT = `
-- Booking Scout Agent
-- Finds gig/festival/residency opportunities that fit the artist's profile.
-- Uses vector search for peer-signal context, then LLM fit scoring.
-- Trigger: on_demand | approval_policy: on_action

function run(ctx)
  mh_log("booking_scout start", ctx.profile_id)

  local profile = mixhive["db.read_one"]("profiles", { id = ctx.profile_id }):await()
  if not profile then
    return { status = "error", message = "profile not found",
             suggestions = {}, tasks = {}, notifications = {} }
  end

  local mixes = mixhive["db.read"]("mixes", { dj_id = ctx.profile_id, published = true }, 5):await()

  -- Vector search for similar artists as peer signal
  local bio_text = string.format("%s %s %s",
    profile.bio or "",
    table.concat(profile.genres or {}, " "),
    profile.dj_style or ""
  )
  local similar = mixhive["vector.search"](bio_text, "profile", 5):await()
  local peer_genres = {}
  for _, s in ipairs(similar) do
    if s.metadata and s.metadata.genres then
      for _, g in ipairs(s.metadata.genres) do
        peer_genres[g] = true
      end
    end
  end

  -- Fetch active booking opportunities
  local opps = mixhive["db.read"]("opportunities", { is_active = true }, 30):await()
  local booking_opps = {}
  for _, o in ipairs(opps) do
    local t = o.opp_type or ""
    if t == "gig" or t == "festival" or t == "residency" then
      table.insert(booking_opps, o)
    end
  end

  if #booking_opps == 0 then
    mh_log("no booking opportunities found")
    return { status = "ok", suggestions = {}, tasks = {}, notifications = {} }
  end

  local opp_lines = {}
  for i, o in ipairs(booking_opps) do
    if i > 15 then break end
    table.insert(opp_lines, string.format(
      "%d. [%s] %s | %s | genres: %s | deadline: %s | comp: %s",
      i,
      o.opp_type or "gig",
      o.title or "?",
      o.city or o.location or "?",
      table.concat(o.genres or {}, ","),
      o.deadline or "open",
      o.compensation or "?"
    ))
  end

  local fit_prompt = string.format([[
You are a booking agent for underground electronic music.
Score which of these opportunities best fit this artist. Return top 5 only.

Artist: %s | Location: %s | Genres: %s | Style: %s
Recent mixes: %d uploaded

Opportunities:
%s

Return JSON only:
{"top_5":[{"index":N,"fit_score":N,"outreach_hook":"string","reason":"string"}]}
fit_score is 0-100. outreach_hook is 1 sentence the artist can use to open the conversation.
]],
    profile.display_name or profile.username or "Artist",
    profile.location or "Belgium",
    table.concat(profile.genres or {}, ", "),
    profile.dj_style or "DJ",
    #mixes,
    table.concat(opp_lines, "\\n")
  )

  local ranked = mixhive["llm.json"](fit_prompt,
    '{"top_5":[{"index":number,"fit_score":number,"outreach_hook":string,"reason":string}]}',
    "haiku"
  ):await()

  local suggs = {}
  local tsks  = {}
  for _, hit in ipairs(ranked.top_5 or {}) do
    local opp = booking_opps[hit.index]
    if opp then
      table.insert(suggs, suggestion(
        "booking_lead",
        {
          opportunity_id  = opp.id,
          title           = opp.title,
          opp_type        = opp.opp_type,
          city            = opp.city or opp.location,
          deadline        = opp.deadline,
          compensation    = opp.compensation,
          fit_score       = hit.fit_score,
          outreach_hook   = hit.outreach_hook,
          reason          = hit.reason,
        },
        (hit.fit_score or 50) / 100,
        hit.reason or "Opportunity matches your profile",
        true
      ))
      table.insert(tsks, task("Contact: " .. (opp.title or "venue"), "high"))
    end
  end

  mh_log("booking_scout found " .. #suggs .. " leads")

  return {
    status        = #suggs > 0 and "needs_approval" or "ok",
    suggestions   = suggs,
    tasks         = tsks,
    notifications = #suggs > 0 and {
      notify(
        "Booking leads ready",
        #suggs .. " opportunities matched your profile — review and approve outreach.",
        "in_app",
        "/agents/inbox"
      )
    } or {},
  }
end
`;

export const COLLABORATION_MATCH = `
-- Collaboration Match Agent
-- Finds complementary artists via vector similarity and drafts intro messages.
-- Trigger: on_demand | approval_policy: on_action

function run(ctx)
  mh_log("collaboration_match start", ctx.profile_id)

  local profile = mixhive["db.read_one"]("profiles", { id = ctx.profile_id }):await()
  if not profile then
    return { status = "error", message = "profile not found",
             suggestions = {}, tasks = {}, notifications = {} }
  end

  local bio_text = string.format("%s %s %s %s",
    profile.bio or "",
    table.concat(profile.genres or {}, " "),
    profile.dj_style or "",
    profile.location or ""
  )

  local similar = mixhive["vector.search"](bio_text, "profile", 10):await()

  -- Filter out own profile
  local candidates = {}
  for _, s in ipairs(similar) do
    if s.entity_id ~= ctx.profile_id and #candidates < 5 then
      table.insert(candidates, s)
    end
  end

  if #candidates == 0 then
    mh_log("no similar profiles found via vector search")
    return { status = "ok", suggestions = {}, tasks = {}, notifications = {} }
  end

  -- Fetch candidate profiles for richer context
  local candidate_lines = {}
  for i, c in ipairs(candidates) do
    if i > 3 then break end
    local meta = c.metadata or {}
    table.insert(candidate_lines, string.format(
      "%d. %s | genres: %s | location: %s | similarity: %.2f",
      i,
      meta.display_name or meta.username or "Artist " .. i,
      table.concat(meta.genres or {}, ", "),
      meta.location or "?",
      c.similarity or 0
    ))
  end

  local intro_prompt = string.format([[
You are a music community connector for underground electronic music.
Draft a warm, direct intro message from one artist to another — no hype, authentic underground tone.
Max 80 words each. Personalise each to the candidate's genre/location.

Sender: %s | %s | %s
Genres: %s

Candidates:
%s

Return JSON only:
{"intros":[{"index":N,"to_name":"string","message":"string"}]}
]],
    profile.display_name or profile.username or "Artist",
    profile.location or "Belgium",
    profile.dj_style or "DJ",
    table.concat(profile.genres or {}, ", "),
    table.concat(candidate_lines, "\\n")
  )

  local result = mixhive["llm.json"](intro_prompt,
    '{"intros":[{"index":number,"to_name":string,"message":string}]}',
    "haiku"
  ):await()

  local suggs = {}
  for _, intro in ipairs(result.intros or {}) do
    local cand = candidates[intro.index]
    table.insert(suggs, suggestion(
      "collab_intro",
      {
        to_profile_id = cand and cand.entity_id or nil,
        to_name       = intro.to_name,
        draft_message = intro.message,
        similarity    = cand and cand.similarity or 0,
      },
      0.70,
      "Complementary style and genre overlap detected via profile embedding",
      true
    ))
  end

  mh_log("collaboration_match found " .. #suggs .. " matches")

  return {
    status        = #suggs > 0 and "needs_approval" or "ok",
    suggestions   = suggs,
    tasks         = {},
    notifications = #suggs > 0 and {
      notify(
        "Collab matches found",
        #suggs .. " artists are a strong fit — review draft intros in your inbox.",
        "in_app",
        "/agents/inbox"
      )
    } or {},
  }
end
`;

export const COMMUNITY_MANAGER = `
-- Community Manager Agent
-- Drafts warm reply suggestions for unanswered comments on the artist's mixes.
-- Trigger: cron:daily | approval_policy: on_action

function run(ctx)
  mh_log("community_manager start", ctx.profile_id)

  local mixes = mixhive["db.read"]("mixes", { dj_id = ctx.profile_id, published = true }, 5):await()

  if #mixes == 0 then
    return { status = "ok", suggestions = {}, tasks = {}, notifications = {} }
  end

  local profile = mixhive["db.read_one"]("profiles", { id = ctx.profile_id }):await()
  local artist_name = (profile and (profile.display_name or profile.username)) or "the artist"

  -- Collect unanswered comments across mixes
  local unanswered = {}
  for _, m in ipairs(mixes) do
    local comments = mixhive["db.read"]("comments", { mix_id = m.id }, 10):await()
    for _, c in ipairs(comments) do
      -- Only include top-level comments not authored by the artist
      if c.author_id ~= ctx.profile_id and not c.parent_id then
        table.insert(unanswered, {
          mix_title   = m.title or "untitled mix",
          mix_id      = m.id,
          comment_id  = c.id,
          author_id   = c.author_id,
          content     = (c.content or ""):sub(1, 150),
        })
        if #unanswered >= 15 then break end
      end
    end
    if #unanswered >= 15 then break end
  end

  if #unanswered == 0 then
    mh_log("no unanswered comments found")
    return { status = "ok", suggestions = {}, tasks = {}, notifications = {} }
  end

  local comment_lines = {}
  for i, c in ipairs(unanswered) do
    if i > 8 then break end
    table.insert(comment_lines, string.format(
      '%d. [on "%s"] "%s"',
      i, c.mix_title, c.content
    ))
  end

  local reply_prompt = string.format([[
You are a community manager for an underground DJ. Draft authentic, warm reply messages.
Tone: personal, unpretentious, underground — not corporate or fan-service-y.
Max 40 words per reply. Match energy of the original comment.
Artist name: %s

Comments to reply to:
%s

Return JSON only:
{"replies":[{"index":N,"draft":"string"}]}
Draft up to 5 replies (skip any you can't improve on).
]],
    artist_name,
    table.concat(comment_lines, "\\n")
  )

  local result = mixhive["llm.json"](reply_prompt,
    '{"replies":[{"index":number,"draft":string}]}',
    "haiku"
  ):await()

  local suggs = {}
  for _, r in ipairs(result.replies or {}) do
    local c = unanswered[r.index]
    if c and r.draft and r.draft ~= "" then
      table.insert(suggs, suggestion(
        "comment_reply_draft",
        {
          mix_id      = c.mix_id,
          comment_id  = c.comment_id,
          mix_title   = c.mix_title,
          original    = c.content,
          draft_reply = r.draft,
        },
        0.70,
        "Drafted reply for unanswered fan comment",
        true
      ))
    end
    if #suggs >= 5 then break end
  end

  mh_log("community_manager drafted " .. #suggs .. " replies")

  return {
    status        = #suggs > 0 and "needs_approval" or "ok",
    suggestions   = suggs,
    tasks         = {},
    notifications = #suggs > 0 and {
      notify(
        "Comment replies ready",
        #suggs .. " draft replies waiting — approve or edit before posting.",
        "in_app",
        "/agents/inbox"
      )
    } or {},
  }
end
`;

export const DJ_SET_ANALYZER = `
-- DJ Set Analyzer Agent (Pro tier)
-- Reads Essentia audio features + tracklist and generates set intelligence.
-- Trigger: event:mix_uploaded

function run(ctx)
  local mix_id = ctx.context and ctx.context.mix_id
  mh_log("dj_set_analyzer start mix=" .. tostring(mix_id))

  if not mix_id then return { status = "error", message = "no mix_id in context",
    suggestions = {}, tasks = {}, notifications = {} } end

  local mix = mixhive["db.read_one"]("mixes", { id = mix_id }):await()
  if not mix then return { status = "error", message = "mix not found",
    suggestions = {}, tasks = {}, notifications = {} } end

  local profile = mixhive["db.read_one"]("profiles", { id = ctx.profile_id }):await()
  if not profile then return { status = "error", message = "profile not found",
    suggestions = {}, tasks = {}, notifications = {} } end

  local features  = mixhive["audio.features"](mix_id):await()
  local tracklist = mixhive["audio.tracklist"](mix_id):await()

  if not features or features.status ~= "complete" then
    mh_log("features not ready — triggering analysis")
    mixhive["audio.trigger_analysis"](mix_id):await()
    return {
      status = "ok",
      suggestions = {},
      tasks = { task("Mix analysis queued — check back in 5 min", "low") },
      notifications = {
        notify("Mix analysis started", "We are analysing your mix. Results soon.", "in_app")
      },
    }
  end

  local analysis_prompt = string.format([[
Analyse this DJ set. Return JSON:
{"set_summary":"3 sentences","scene_classification":"label",
 "energy_arc":"description","suggested_tags":["tag"],
 "bookability_assessment":"1 sentence",
 "release_candidate":true/false,"release_reason":"1 sentence"}

BPM: %s | Key: %s | Mood: %s | Energy: %s | Danceability: %s
Duration: %s min | Tracks identified: %d | Artist: %s
]],
    tostring(features.bpm or "?"),
    features.camelot or features.musical_key or "?",
    features.mood or "?",
    tostring(features.energy or "?"),
    tostring(features.danceability or "?"),
    tostring(math.floor((mix.duration_seconds or 0) / 60)),
    #tracklist,
    profile.display_name or "unknown"
  )

  local report = mixhive["llm.json"](analysis_prompt,
    '{"set_summary":string,"scene_classification":string,"energy_arc":string,"suggested_tags":["string"],"bookability_assessment":string,"release_candidate":boolean,"release_reason":string}',
    "sonnet"
  ):await()

  if not ctx.dry_run then
    mixhive["db.update"]("mixes", { id = mix_id }, {
      tags = report.suggested_tags,
    }):await()
  end

  local suggestions = {
    suggestion(
      "mix_analysis_complete",
      {
        mix_id          = mix_id,
        report          = report,
        tracklist_count = #tracklist,
        bpm             = features.bpm,
        key             = features.camelot or features.musical_key,
        mood            = features.mood,
      },
      0.90,
      "Full AI analysis — tracklist, energy arc, scene classification",
      false
    )
  }

  if report.release_candidate then
    table.insert(suggestions, suggestion(
      "release_candidate",
      { mix_id = mix_id, reason = report.release_reason },
      0.80,
      "Release potential: " .. (report.release_reason or ""),
      false
    ))
  end

  mh_log("analysis done scene=" .. (report.scene_classification or "?"))
  return {
    status        = "ok",
    suggestions   = suggestions,
    tasks         = {},
    notifications = {
      notify(
        "Mix analysis complete",
        "Scene: " .. (report.scene_classification or "?") ..
        " | BPM: " .. tostring(features.bpm or "?") ..
        " | " .. #tracklist .. " tracks",
        "in_app",
        "/mixes/" .. mix_id
      )
    },
  }
end
`;

export const EVENT_ORGANIZER = `
-- Event Organizer Agent
-- Helps partners assemble 4-act lineups from available booking-open artists.
-- Trigger: on_demand | approval_policy: always (partner tier)

function run(ctx)
  mh_log("event_organizer start", ctx.profile_id)

  -- Fetch artists who have opted into booking
  local goals = mixhive["db.read"]("artist_goals", { booking_open = true }, 20):await()

  if #goals == 0 then
    mh_log("no booking-open artists found")
    return { status = "ok", suggestions = {}, tasks = {}, notifications = {} }
  end

  -- Fetch profile details for each artist
  local artist_lines = {}
  for i, g in ipairs(goals) do
    if i > 15 then break end
    local profile = mixhive["db.read_one"]("profiles", { id = g.user_id }):await()
    if profile then
      local mixes = mixhive["db.read"]("mixes", { dj_id = g.user_id, published = true }, 3):await()
      table.insert(artist_lines, string.format(
        "%d. %s | %s | genres: %s | mixes: %d | skills: %s",
        i,
        profile.display_name or profile.username or "Artist",
        profile.location or "Belgium",
        table.concat(profile.genres or {}, ", "),
        #mixes,
        table.concat(g.skills or {}, ", ")
      ))
    end
  end

  -- Read event context from opportunities if organizer has one
  local event_context = ""
  local opp = mixhive["db.read_one"]("opportunities", { opp_type = "festival" }):await()
  if opp then
    event_context = string.format("Event context: %s | %s | %s",
      opp.title or "Festival",
      opp.city or "Belgium",
      table.concat(opp.genres or {}, ", "))
  end

  local lineup_prompt = string.format([[
You are a rave booking agent for the Belgian underground electronic scene.
Assemble a 4-act lineup from the available artists. Think: narrative arc, genre flow, energy build.
Roles: headliner (peak time), main support (pre-headliner), opener, wildcard (experimental/different genre).

%s

Available artists:
%s

Return JSON only:
{
  "lineup": [
    {"role":"headliner","artist_index":N,"slot_time":"HH:MM","set_length_min":N,"rationale":"string"},
    {"role":"main_support","artist_index":N,"slot_time":"HH:MM","set_length_min":N,"rationale":"string"},
    {"role":"opener","artist_index":N,"slot_time":"HH:MM","set_length_min":N,"rationale":"string"},
    {"role":"wildcard","artist_index":N,"slot_time":"HH:MM","set_length_min":N,"rationale":"string"}
  ],
  "event_concept": "string"
}
]],
    event_context,
    table.concat(artist_lines, "\\n")
  )

  local lineup = mixhive["llm.json"](lineup_prompt,
    '{"lineup":[{"role":string,"artist_index":number,"slot_time":string,"set_length_min":number,"rationale":string}],"event_concept":string}',
    "sonnet"
  ):await()

  local suggs = {}
  for _, slot in ipairs(lineup.lineup or {}) do
    local g = goals[slot.artist_index]
    table.insert(suggs, suggestion(
      "slot_suggestion",
      {
        role          = slot.role,
        artist_id     = g and g.user_id or nil,
        slot_time     = slot.slot_time,
        set_length_min = slot.set_length_min,
        rationale     = slot.rationale,
        event_concept = lineup.event_concept,
      },
      0.80,
      "Lineup assembled from booking-open artists on MixHive",
      true
    ))
  end

  mh_log("event_organizer built lineup with " .. #suggs .. " slots")

  return {
    status        = "needs_approval",
    suggestions   = suggs,
    tasks         = {
      task("Confirm artist availability for each slot", "high"),
      task("Draft event announcement copy", "medium"),
    },
    notifications = {
      notify(
        "Lineup draft ready",
        "4-act lineup assembled — concept: " .. (lineup.event_concept or "TBD"),
        "in_app",
        "/agents/inbox"
      )
    },
  }
end
`;

export const FAN_INSIGHTS = `
-- Fan Insights Agent
-- Clusters audience from likes, play history, and analytics events.
-- Trigger: cron:weekly | approval_policy: auto (pro tier)

function run(ctx)
  mh_log("fan_insights start", ctx.profile_id)

  -- Get user's mixes to join against engagement tables
  local mixes = mixhive["db.read"]("mixes", { dj_id = ctx.profile_id, published = true }, 20):await()

  if #mixes == 0 then
    mh_log("no published mixes found")
    return { status = "ok", suggestions = {}, tasks = {}, notifications = {} }
  end

  -- Aggregate likes across mixes
  local total_likes = 0
  local mix_engagement = {}
  for _, m in ipairs(mixes) do
    local lc = m.likes_count or 0
    local pc = m.play_count  or 0
    total_likes = total_likes + lc
    if lc + pc > 0 then
      table.insert(mix_engagement, string.format(
        "- %s: %d plays, %d likes, tags: %s",
        m.title or "untitled", pc, lc,
        table.concat(m.tags or {}, ", ")
      ))
    end
  end

  -- Read analytics events
  local events = mixhive["db.read"]("analytics_events", { profile_id = ctx.profile_id }, 50):await()
  local event_summary = {}
  local event_counts = {}
  for _, e in ipairs(events) do
    local t = e.event_type or "unknown"
    event_counts[t] = (event_counts[t] or 0) + 1
  end
  for t, c in pairs(event_counts) do
    table.insert(event_summary, t .. ": " .. c)
  end

  -- Read follow data
  local followers = mixhive["db.read"]("follows", { following_id = ctx.profile_id }, 50):await()

  local cluster_prompt = string.format([[
You are an audience analytics specialist for underground electronic music.
Cluster this DJ's audience into 3 distinct segments based on engagement signals.

Artist: %s | Total mixes: %d | Total likes: %d | Followers: %d

Mix engagement (top %d):
%s

Platform events:
%s

Return JSON only:
{
  "segments": [
    {
      "label": "string",
      "size_pct": N,
      "behaviour": "string",
      "action_tip": "string"
    }
  ],
  "top_performing_tag": "string",
  "growth_insight": "string"
}
]],
    ctx.profile_id,
    #mixes,
    total_likes,
    #followers,
    math.min(#mix_engagement, 10),
    table.concat(mix_engagement, "\\n"):sub(1, 800),
    table.concat(event_summary, ", "):sub(1, 200)
  )

  local clusters = mixhive["llm.json"](cluster_prompt,
    '{"segments":[{"label":string,"size_pct":number,"behaviour":string,"action_tip":string}],"top_performing_tag":string,"growth_insight":string}',
    "sonnet"
  ):await()

  mh_log("fan_insights clusters generated")

  return {
    status = "ok",
    suggestions = {
      suggestion(
        "fan_cluster_report",
        clusters,
        0.80,
        "Audience segmentation from " .. #mixes .. " mixes and " .. #followers .. " followers",
        false
      )
    },
    tasks = {},
    notifications = {
      notify(
        "Fan insights ready",
        "Your audience report is ready — top tag: " .. (clusters.top_performing_tag or "?"),
        "in_app",
        "/agents/inbox"
      )
    },
  }
end
`;

export const GRANT_ASSISTANT = `
-- Grant Assistant Agent
-- Scores eligibility for Belgian and EU music grants, drafts application intros.
-- Trigger: event:user_request | cron:weekly

local GRANTS = {
  {
    id          = "sabam_culture",
    name        = "Sabam for Culture",
    org         = "Sabam",
    country     = "BE",
    max_amount  = 5000,
    description = "Supports Belgian creators for cultural projects. Members only.",
    eligibility = "Must be Sabam member. Belgian nationality or residence.",
    url         = "https://www.sabam.be",
  },
  {
    id          = "playright_plus",
    name        = "PlayRight+ Music Video Grant",
    org         = "PlayRight",
    country     = "BE",
    max_amount  = 750,
    description = "Half of production costs (max 750 EUR) for a music video or live session.",
    eligibility = "Must be a PlayRight beneficiary (performer/musician).",
    url         = "https://playright.be",
  },
  {
    id          = "fund_belgian_music",
    name        = "Fund Belgian Music",
    org         = "FACIR / Sabam for Culture / PlayRight+",
    country     = "BE",
    max_amount  = 7500,
    description = "Max 30% of budget, capped at 7500 EUR. Belgian music projects with cultural impact.",
    eligibility = "Belgian professional musician or collective.",
    url         = "https://kbs-frb.be",
  },
  {
    id          = "effea",
    name        = "EFFEA — European Festivals Fund for Emerging Artists",
    org         = "EFFEA",
    country     = "EU",
    max_amount  = 15000,
    description = "Supports emerging artists performing at European festivals.",
    eligibility = "Emerging artist (not yet headline). European nationality or residence.",
    url         = "https://www.effa.info",
  },
}

function run(ctx)
  mh_log("grant_assistant start", ctx.profile_id)

  local profile = mixhive["db.read_one"]("profiles", { id = ctx.profile_id }):await()
  if not profile then return { status = "error", message = "profile not found",
    suggestions = {}, tasks = {}, notifications = {} } end

  local country = (profile.location or ""):match("^(%a+)") or "BE"

  local suggestions  = {}
  local tasks        = {}
  local notifications = {}

  for _, grant in ipairs(GRANTS) do
    if grant.country ~= "EU" and grant.country ~= "BE" then goto continue end

    local score_prompt = string.format([[
Score this artist's eligibility for this grant. Return JSON:
{"score":0-100,"eligible":true/false,"reason":"1 sentence","missing":["item1"]}

Artist: %s | Location: %s | Genres: %s | Bio: %s
Grant: %s | Criteria: %s
]],
      profile.display_name or "Artist",
      profile.location or "unknown",
      table.concat(profile.genres or {}, ", "),
      (profile.bio or ""):sub(1, 200),
      grant.name,
      grant.eligibility
    )

    local elig = mixhive["llm.json"](score_prompt,
      '{"score":number,"eligible":boolean,"reason":string,"missing":["string"]}',
      "haiku"
    ):await()

    mh_log(grant.name .. " score=" .. tostring(elig.score))

    if (elig.score or 0) >= 55 then
      local draft_prompt = string.format([[
Write the opening paragraph (max 120 words) of a grant application from "%s" for "%s".
Artist bio: %s | Location: %s | Genres: %s
Grant purpose: %s
Tone: professional, specific, concrete plans. Not generic.
]],
        profile.display_name or "the artist",
        grant.name,
        (profile.bio or ""):sub(1, 150),
        profile.location or "Belgium",
        table.concat(profile.genres or {}, ", "),
        grant.description:sub(1, 150)
      )
      local draft = mixhive["llm.call"](draft_prompt, "sonnet"):await()

      table.insert(suggestions, suggestion(
        "grant_opportunity",
        {
          grant_id          = grant.id,
          grant_name        = grant.name,
          org               = grant.org,
          max_amount        = grant.max_amount,
          url               = grant.url,
          eligibility_score = elig.score,
          missing           = elig.missing,
          draft_intro       = draft,
        },
        elig.score / 100,
        elig.reason,
        true
      ))
      table.insert(tasks, task(
        "Complete application: " .. grant.name .. " (max " .. tostring(grant.max_amount) .. " EUR)",
        "high"
      ))
    end

    ::continue::
  end

  if #suggestions > 0 then
    table.insert(notifications, notify(
      tostring(#suggestions) .. " grant opportunities found",
      "You may be eligible for funding. Review draft applications.",
      "email",
      "/agents/inbox"
    ))
  end

  mh_log("done — " .. #suggestions .. " grants")
  return {
    status        = #suggestions > 0 and "needs_approval" or "ok",
    suggestions   = suggestions,
    tasks         = tasks,
    notifications = notifications,
  }
end
`;

export const LABEL_SCOUT = `
-- Label Scout Agent
-- Finds labels and collectives that fit an artist via opportunities + vector search.
-- Trigger: on_demand | approval_policy: on_action (pro tier)

function run(ctx)
  mh_log("label_scout start", ctx.profile_id)

  local profile = mixhive["db.read_one"]("profiles", { id = ctx.profile_id }):await()
  if not profile then
    return { status = "error", message = "profile not found",
             suggestions = {}, tasks = {}, notifications = {} }
  end

  local mixes = mixhive["db.read"]("mixes", { dj_id = ctx.profile_id, published = true }, 5):await()

  -- Collab-call and radio opportunities often represent labels/collectives
  local opps = mixhive["db.read"]("opportunities", { is_active = true }, 30):await()
  local label_opps = {}
  for _, o in ipairs(opps) do
    local t = o.opp_type or ""
    if t == "collab_call" or t == "radio" then
      -- Check genre overlap
      local overlap = false
      for _, og in ipairs(o.genres or {}) do
        for _, pg in ipairs(profile.genres or {}) do
          if og == pg then overlap = true end
        end
      end
      if overlap or #(o.genres or {}) == 0 then
        table.insert(label_opps, o)
      end
    end
  end

  -- Vector search for established artists/labels in same space
  local bio_text = string.format("%s %s",
    table.concat(profile.genres or {}, " "),
    profile.bio or ""
  )
  local similar = mixhive["vector.search"](bio_text, "profile", 8):await()

  local opp_lines = {}
  for i, o in ipairs(label_opps) do
    if i > 10 then break end
    table.insert(opp_lines, string.format(
      "%d. [%s] %s | %s | organizer: %s | url: %s",
      i, o.opp_type or "?",
      o.title or "?",
      o.city or "?",
      o.organizer or "?",
      o.source_url or "?"
    ))
  end

  local similar_lines = {}
  for i, s in ipairs(similar) do
    if i > 5 then break end
    local meta = s.metadata or {}
    table.insert(similar_lines, string.format(
      "- %s | %s | sim: %.2f",
      meta.display_name or meta.username or "Artist",
      table.concat(meta.genres or {}, ", "),
      s.similarity or 0
    ))
  end

  local fit_prompt = string.format([[
You are a music industry advisor for underground electronic artists.
Identify the 5 best label/collective fits for this artist.
Use both the open calls and peer artist signals to identify which imprints would be interested.

Artist: %s | Location: %s | Genres: %s | Mixes: %d
Bio: %s

Open calls from labels/collectives:
%s

Similar artists on platform (peer signal):
%s

Return JSON only:
{
  "top_5": [
    {
      "label_name": "string",
      "source": "opportunity|inference",
      "opportunity_index": N or null,
      "fit_score": N,
      "pitch_angle": "string"
    }
  ]
}
]],
    profile.display_name or profile.username or "Artist",
    profile.location or "Belgium",
    table.concat(profile.genres or {}, ", "),
    #mixes,
    (profile.bio or ""):sub(1, 200),
    #opp_lines > 0 and table.concat(opp_lines, "\\n") or "None found",
    #similar_lines > 0 and table.concat(similar_lines, "\\n") or "None found"
  )

  local ranked = mixhive["llm.json"](fit_prompt,
    '{"top_5":[{"label_name":string,"source":string,"opportunity_index":number,"fit_score":number,"pitch_angle":string}]}',
    "haiku"
  ):await()

  local suggs = {}
  for _, hit in ipairs(ranked.top_5 or {}) do
    local opp = hit.opportunity_index and label_opps[hit.opportunity_index] or nil
    table.insert(suggs, suggestion(
      "label_fit",
      {
        label_name      = hit.label_name,
        fit_score       = hit.fit_score,
        pitch_angle     = hit.pitch_angle,
        source          = hit.source,
        opportunity_id  = opp and opp.id or nil,
        source_url      = opp and opp.source_url or nil,
      },
      (hit.fit_score or 50) / 100,
      "Label fit based on genre alignment and open call analysis",
      true
    ))
  end

  mh_log("label_scout found " .. #suggs .. " label fits")

  return {
    status        = #suggs > 0 and "needs_approval" or "ok",
    suggestions   = suggs,
    tasks         = #suggs > 0 and {
      task("Research and prepare pitch for top label fit", "high"),
    } or {},
    notifications = #suggs > 0 and {
      notify(
        "Label matches ready",
        "Found " .. #suggs .. " label/collective fits — review pitch angles in your inbox.",
        "in_app",
        "/agents/inbox"
      )
    } or {},
  }
end
`;

export const MODERATION = `
-- Moderation Agent
-- Screens content for harmful signals. Underground-culture-aware.
-- Trigger: event:content_created

function run(ctx)
  local content_id   = ctx.context and ctx.context.content_id
  local content_type = ctx.context and ctx.context.content_type or "post"
  mh_log("moderation start", content_type, content_id)

  if not content_id then return { status = "error", message = "no content_id",
    suggestions = {}, tasks = {}, notifications = {} } end

  local content = mixhive["db.read_one"](content_type .. "s", { id = content_id }):await()
  if not content then return { status = "error", message = "content not found",
    suggestions = {}, tasks = {}, notifications = {} } end

  local text = content.body or content.description or content.bio or ""

  local mod_prompt = string.format([[
Moderate content for an underground electronic music platform. Return JSON only:
{"action":"allow"|"warn"|"hide"|"escalate","severity":0-10,
 "flags":["hate_speech"|"spam"|"fraud"|"doxxing"|"harassment"|"none"],
 "reason":"1 sentence"}

Context: drug references in harm-reduction context, profanity, adult themes,
rave culture language are NORMAL here. Only flag: hate speech based on protected
characteristics, fraud, doxxing, CSAM, violent threats.

Content type: %s
Text: %s
]],
    content_type,
    text:sub(1, 800)
  )

  local result = mixhive["llm.json"](mod_prompt,
    '{"action":string,"severity":number,"flags":["string"],"reason":string}',
    "haiku"
  ):await()

  mh_log("action=" .. (result.action or "?") .. " severity=" .. tostring(result.severity))

  if not ctx.dry_run then
    mixhive["db.insert"]("moderation_signals", {
      source_table  = content_type .. "s",
      source_id     = content_id,
      signal_type   = table.concat(result.flags or {}, ","),
      severity      = result.severity or 0,
      action_taken  = result.action or "allow",
    }):await()

    if result.action == "hide" or result.action == "escalate" then
      mixhive["db.update"](content_type .. "s", { id = content_id }, {
        moderation_status = result.action,
        moderation_reason = result.reason,
      }):await()
    end
  end

  local suggestions = {}
  if result.action == "escalate" then
    table.insert(suggestions, suggestion(
      "moderation_escalation",
      { content_id = content_id, content_type = content_type, result = result },
      1.0,
      result.reason,
      true
    ))
  end

  return {
    status        = result.action == "escalate" and "needs_approval" or "ok",
    suggestions   = suggestions,
    tasks         = {},
    notifications = {},
  }
end
`;

export const MYTHIC_COLLAB_WEAVER = `
-- Mythic Collab Weaver Agent (Strategic)
-- Finds high-yield collaboration opportunities using MythicNode graph triangles + historical yield.

function run(ctx)
  mh_log("mythic_collab_weaver start", ctx.profile_id)

  local profile = mixhive["db.read_one"]("profiles", { id = ctx.profile_id }):await()
  if not profile then
    return error_response("profile not found")
  end

  -- Pull graph signals
  local recent_collabs = mixhive["db.read"]("mythic_edges", {
    from_node_id = ctx.profile_id,
    edge_type = "collab_with"
  }, 10):await() or {}

  local recent_venues = mixhive["db.read"]("mythic_edges", {
    from_node_id = ctx.profile_id,
    edge_type = "performed_at"
  }, 12):await() or {}

  local prompt = string.format([[
You are the Mythic Collab Weaver — a strategic matchmaker that uses real graph data.

Artist: %s (genres: %s, location: %s)
Recent collabs logged: %d
Recent venues performed at: %d

Propose 2-3 high-potential collab missions.
Prioritize artists with:
- Shared venue history (strong signal)
- Complementary audience/engagement patterns
- Historical conversion into releases or joint gigs for similar profiles

Return JSON:
{
  "collab_missions": [
    {
      "target_artist_name": string,
      "rationale": string,
      "suggested_first_move": string,
      "confidence": number
    }
  ]
}
]], profile.display_name or "artist", table.concat(profile.genres or {}, ", "), profile.location or "unknown", #recent_collabs, #recent_venues)

  local result = mixhive["llm.json"](prompt, nil, "sonnet"):await()

  local suggestions = {}
  for _, m in ipairs(result.collab_missions or {}) do
    table.insert(suggestions, suggestion(
      "mythic_collab_mission",
      m,
      m.confidence or 0.68,
      m.rationale,
      true
    ))
  end

  return {
    status = "ok",
    suggestions = suggestions,
    tasks = {},
    notifications = {},
  }
end

function error_response(msg)
  return { status = "error", message = msg, suggestions = {}, tasks = {}, notifications = {} }
end
`;

export const MYTHIC_NARRATOR = `
-- Mythic Narrator Agent (Strategic)
-- Writes living, graph-grounded career narrative chapters.

function run(ctx)
  mh_log("mythic_narrator start", ctx.profile_id)

  local profile = mixhive["db.read_one"]("profiles", { id = ctx.profile_id }):await()
  if not profile then
    return error_response("profile not found")
  end

  local recent_edges = mixhive["db.read"]("mythic_edges", {
    from_node_id = ctx.profile_id
  }, 15):await() or {}

  local prompt = string.format([[
You are the Mythic Narrator — calm, precise, anti-hype career archivist.

Write one short "Chapter" (140-180 words) for this artist.

Artist: %s | %s | %s
Recent MythicNode activity: %d recorded edges (gigs, submissions, collabs, etc.)

Tone: reflective and data-grounded. Reference real momentum and one clear recommended focus. Never hype.
]], profile.display_name or "Artist", profile.location or "unknown", table.concat(profile.genres or {}, ", "), #recent_edges)

  local chapter = mixhive["llm.call"](prompt, "haiku"):await()

  return {
    status = "ok",
    suggestions = {
      suggestion("career_chapter", { chapter = chapter }, 0.82, "New narrative chapter", false)
    },
    tasks = {},
    notifications = {
      notify("New Chapter Ready", "Your latest career chapter has been written.", "in_app", "/agents")
    },
  }
end

function error_response(msg)
  return { status = "error", message = msg, suggestions = {}, tasks = {}, notifications = {} }
end
`;

export const MYTHIC_SCENE_ORBIT = `
-- Mythic Scene Orbit Agent (Strategic)
-- Maintains long-term career quests and proposes high-signal actions using the MythicNode graph.

function run(ctx)
  mh_log("mythic_scene_orbit start", ctx.profile_id)

  local profile = mixhive["db.read_one"]("profiles", { id = ctx.profile_id }):await()
  if not profile then
    return error_response("profile not found")
  end

  -- Rich MythicNode context (strategic agents can query these tables)
  local recent_performances = mixhive["db.read"]("mythic_edges", {
    from_node_id = ctx.profile_id,
    edge_type = "performed_at"
  }, 20):await() or {}

  local recent_submissions = mixhive["db.read"]("mythic_edges", {
    from_node_id = ctx.profile_id,
    edge_type = "submitted_to"
  }, 15):await() or {}

  local active_quests = mixhive["db.read"]("quests", {
    owner_id = ctx.profile_id,
    status = "active"
  }, 3):await() or {}

  local quest_context = ""
  if #active_quests > 0 then
    local q = active_quests[1]
    local milestones = mixhive["db.read"]("quest_milestones", { quest_id = q.id }, 8):await() or {}
    quest_context = string.format('Active Quest: "%s" (momentum: %s, %d milestones)',
      q.title, q.momentum or "?", #milestones)
  end

  local prompt = string.format([[
You are the Mythic Scene Orbit strategic agent — a calm, data-driven career navigator for underground electronic creators.

Artist: %s
Location: %s
Genres: %s

Recent MythicNode signals (last 12 months):
- Real performances logged: %d
- Opportunity submissions: %d
- %s

Your job:
- If they have an active scene-focused quest, propose 2-3 high-leverage next actions (specific venues, promoters, or micro-collabs with historical yield for similar artists in that scene).
- If no strong active quest exists, recommend one high-potential focus area right now.
- Ground every suggestion in actual graph data (shared venues, overlapping success patterns, etc.).

Return strict JSON only:
{
  "recommended_focus": string,
  "actions": [
    {
      "title": string,
      "rationale": string,
      "target_type": "venue" | "opportunity" | "artist" | "collab",
      "confidence": number (0.0-1.0)
    }
  ]
}

Tone: insider, precise, anti-hype. Max 2-3 actions.
]], 
    profile.display_name or "Artist",
    profile.location or "unknown",
    table.concat(profile.genres or {}, ", "),
    #recent_performances,
    #recent_submissions,
    quest_context ~= "" and quest_context or "No active scene quest currently"
  )

  local plan = mixhive["llm.json"](prompt, nil, "sonnet"):await()

  local suggestions = {}
  local notifications = {}

  for _, action in ipairs(plan.actions or {}) do
    table.insert(suggestions, suggestion(
      "mythic_scene_action",
      action,
      action.confidence or 0.72,
      action.rationale,
      true
    ))
  end

  if plan.recommended_focus then
    table.insert(notifications, notify(
      "Scene Orbit Focus",
      plan.recommended_focus,
      "in_app",
      "/agents"
    ))
  end

  return {
    status = "ok",
    suggestions = suggestions,
    tasks = {},
    notifications = notifications,
  }
end

function error_response(msg)
  return {
    status = "error",
    message = msg,
    suggestions = {},
    tasks = {},
    notifications = {},
  }
end`;

export const MYTHIC_YIELD_ANALYST = `
-- Mythic Yield Analyst (Strategic)
-- The "Career Scientist" — surfaces which actions actually produced real outcomes using MythicNode attribution.

function run(ctx)
  mh_log("mythic_yield_analyst start", ctx.profile_id)

  local profile = mixhive["db.read_one"]("profiles", { id = ctx.profile_id }):await()
  if not profile then
    return error_response("profile not found")
  end

  -- Pull outcome data
  local yielded_outcomes = mixhive["db.read"]("mythic_edges", {
    from_node_id = ctx.profile_id,
    edge_type = "yielded_outcome"
  }, 10):await() or {}

  local recent_actions = mixhive["db.read"]("mythic_edges", {
    from_node_id = ctx.profile_id
  }, 25):await() or {}

  local prompt = string.format([[
You are the Mythic Yield Analyst — cold, honest, pattern-obsessed.

Artist: %s
Recent MythicNode activity: %d edges
Attributed real-world outcomes: %d

Analyze and identify:
1. 1-2 patterns with the highest real yield (bookings, strong responses, releases).
2. One low-yield pattern worth deprioritizing.

Return JSON:
{
  "high_yield": [{ "pattern": string, "evidence": string, "lift": number }],
  "low_yield": { "pattern": string, "recommendation": string }
}
]], profile.display_name or "artist", #recent_actions, #yielded_outcomes)

  local analysis = mixhive["llm.json"](prompt, nil, "sonnet"):await()

  local suggestions = {}
  if analysis.high_yield then
    for _, item in ipairs(analysis.high_yield) do
      table.insert(suggestions, suggestion("double_down_pattern", item, 0.78, item.evidence, true))
    end
  end

  return {
    status = "ok",
    suggestions = suggestions,
    tasks = {},
    notifications = {
      notify("Yield Review Ready", "Your latest career yield analysis is available.", "in_app", "/agents")
    },
  }
end

function error_response(msg)
  return { status = "error", message = msg, suggestions = {}, tasks = {}, notifications = {} }
end
`;

export const NOTIFICATION_PRIORITIZER = `
-- Notification Prioritizer Agent
-- Reduces notification noise: picks top 3 highest-priority unread notifications.
-- Trigger: cron:hourly

function run(ctx)
  mh_log("notification_prioritizer start", ctx.profile_id)

  local pending = mixhive["db.read"]("notifications", {
    profile_id = ctx.profile_id,
    read       = false,
  }, 50):await()

  if #pending == 0 then
    return { status = "ok", suggestions = {}, tasks = {}, notifications = {} }
  end

  mh_log("pending=" .. #pending)

  local lines = {}
  for i, n in ipairs(pending) do
    table.insert(lines, string.format("%d. [%s] %s", i, n.type or "?", (n.message or ""):sub(1, 60)))
  end

  local rank_prompt = string.format([[
Rank these %d notifications for a DJ/producer. Select the top 3 by urgency.
Prioritise: deadlines, booking opportunities, grants, direct messages.
De-prioritise: generic likes/follows.
Return JSON: {"top_3_indices":[1,5,12],"digest":"1 sentence summary"}

Notifications:
%s
]],
    #pending,
    table.concat(lines, "\\n"):sub(1, 1500)
  )

  local ranked = mixhive["llm.json"](rank_prompt,
    '{"top_3_indices":[number],"digest":string}',
    "haiku"
  ):await()

  local daily_notifs = {}
  for _, idx in ipairs(ranked.top_3_indices or {1}) do
    local n = pending[idx]
    if n then
      table.insert(daily_notifs, notify(
        n.title or "Update",
        n.message or "",
        "in_app",
        n.action_url
      ))
    end
  end

  if ranked.digest then
    table.insert(daily_notifs, notify("Today's digest", ranked.digest, "in_app", "/dashboard"))
  end

  mh_log("surfaced " .. #daily_notifs .. " notifications")
  return {
    status        = "ok",
    suggestions   = {},
    tasks         = {},
    notifications = daily_notifs,
  }
end
`;

export const OPPORTUNITY_MATCH = `
-- Opportunity Match Agent
-- Matches artist to grants, gigs, open calls, and festivals from ai_suggestions + opportunities table.
-- Trigger: cron:hourly | event:user_request

function run(ctx)
  mh_log("opportunity_match start", ctx.profile_id)

  local profile = mixhive["db.read_one"]("profiles", { id = ctx.profile_id }):await()
  if not profile then return { status = "error", message = "profile not found",
    suggestions = {}, tasks = {}, notifications = {} } end

  -- Load open opportunities
  local opps = mixhive["db.read"]("opportunities", { is_active = true }, 20):await()

  if #opps == 0 then
    mh_log("no active opportunities found")
    return { status = "ok", suggestions = {}, tasks = {}, notifications = {} }
  end

  local suggestions = {}
  local count = 0

  for _, opp in ipairs(opps) do
    if count >= 8 then break end

    local rationale_prompt = string.format([[
In 1 sentence, explain why "%s" (genres: %s, location: %s) fits this opportunity:
"%s" — %s
Be specific. Max 20 words.
]],
      profile.display_name or "this artist",
      table.concat(profile.genres or {}, ", "),
      profile.location or "Belgium",
      opp.title or "opportunity",
      (opp.description or ""):sub(1, 150)
    )

    local rationale = mixhive["llm.call"](rationale_prompt, "haiku"):await()

    table.insert(suggestions, suggestion(
      "opportunity_match",
      {
        opportunity_id = opp.id,
        title          = opp.title,
        opp_type       = opp.opp_type,
        city           = opp.city,
        compensation   = opp.compensation,
        deadline       = opp.deadline,
        source_url     = opp.source_url,
      },
      0.70,
      rationale,
      false
    ))
    count = count + 1
  end

  local notifications = {}
  if #suggestions > 0 then
    table.insert(notifications, notify(
      #suggestions .. " opportunities matched",
      "New gigs, grants, and open calls matched to your profile.",
      "in_app",
      "/agents/inbox"
    ))
  end

  mh_log("done — " .. #suggestions .. " matches")
  return {
    status        = "ok",
    suggestions   = suggestions,
    tasks         = {},
    notifications = notifications,
  }
end
`;

export const PRESS_KIT = `
-- Press Kit Agent
-- Generates a complete EPK for the artist. Trigger: event:user_request

function run(ctx)
  mh_log("press_kit start", ctx.profile_id)

  local profile = mixhive["db.read_one"]("profiles", { id = ctx.profile_id }):await()
  if not profile then return { status = "error", message = "profile not found",
    suggestions = {}, tasks = {}, notifications = {} } end

  local mixes = mixhive["db.read"]("mixes", { dj_id = ctx.profile_id, published = true }, 3):await()

  local epk_prompt = string.format([[
Write a professional Electronic Press Kit for an underground DJ/producer.
Return JSON only — no backticks or markdown.
{
  "headline": "one punchy sentence",
  "bio_short": "max 80 words",
  "bio_long": "max 200 words",
  "genre_tags": ["tag1","tag2"],
  "technical_rider_stub": "4-line standard rider",
  "booking_email_template": "short email template with subject line",
  "press_quote": "[PLACEHOLDER — replace with real press quote]"
}
Artist: %s | Location: %s | Genres: %s
Bio: %s
Published mixes: %d
]],
    profile.display_name or "Artist",
    profile.location or "Belgium",
    table.concat(profile.genres or {}, ", "),
    (profile.bio or ""):sub(1, 400),
    #mixes
  )

  local epk = mixhive["llm.json"](epk_prompt,
    '{"headline":string,"bio_short":string,"bio_long":string,"genre_tags":["string"],"technical_rider_stub":string,"booking_email_template":string,"press_quote":string}',
    "sonnet"
  ):await()

  -- Merge real social links
  epk.social_links = profile.social_links or {}

  if not ctx.dry_run then
    mixhive["db.upsert"]("press_kits", {
      profile_id   = ctx.profile_id,
      version      = 1,
      content_json = epk,
      public_slug  = ctx.profile_id,
    }):await()
  end

  mh_log("EPK generated")
  return {
    status = "needs_approval",
    suggestions = {
      suggestion(
        "press_kit_generated",
        { epk = epk, public_url = "/epk/" .. ctx.profile_id },
        0.95,
        "EPK generated from your profile — review before sharing",
        true
      )
    },
    tasks = { task("Review and publish your Press Kit", "high") },
    notifications = {
      notify("Your Press Kit is ready", "Review and share with promoters.", "in_app", "/dashboard/press-kit")
    },
  }
end
`;

export const PROFILE_COACH = `
-- Profile Coach Agent
-- Scores a DJ/producer profile on 5 axes and surfaces targeted improvements.
-- Trigger: event:profile_updated | cron:weekly | event:user_request

function run(ctx)
  mh_log("profile_coach start", ctx.profile_id)

  local profile = mixhive["db.read_one"]("profiles", { id = ctx.profile_id }):await()
  if not profile then
    return { status = "error", message = "profile not found",
             suggestions = {}, tasks = {}, notifications = {} }
  end

  local mixes = mixhive["db.read"]("mixes", { dj_id = ctx.profile_id, published = true }, 5):await()

  local score_prompt = string.format([[
Score this DJ/producer profile for bookability. Return JSON only:
{ "bio": N, "visuals": N, "mix_quality": N, "social_proof": N, "overall": N, "weakest": "axis" }
Each axis 0-100. Strict scoring: blank bio=0, no avatar=10, no mixes=20.

Name: %s
Bio (%d chars): %s
Avatar: %s
Mixes uploaded: %d
Location: %s
Genres: %s
]],
    profile.display_name or "unnamed",
    #(profile.bio or ""),
    (profile.bio or ""):sub(1, 400),
    profile.avatar_url and "set" or "missing",
    #mixes,
    profile.location or "not set",
    table.concat(profile.genres or {}, ", ")
  )

  local score = mixhive["llm.json"](score_prompt,
    '{"bio":number,"visuals":number,"mix_quality":number,"social_proof":number,"overall":number,"weakest":string}',
    "haiku"
  ):await()

  mh_log("score overall=" .. tostring(score.overall))

  local suggestions = {}
  local tasks = {}
  local notifications = {}

  -- Bio suggestion
  if (score.bio or 0) < 60 then
    local bio_prompt = string.format([[
Write a punchy 3-sentence artist bio for this underground DJ/producer.
Name: %s | Location: %s | Genres: %s
Existing bio: %s
Style: honest, underground, first-person. Max 100 words. Include one memorable hook.
]],
      profile.display_name or "this artist",
      profile.location or "Belgium",
      table.concat(profile.genres or {}, ", "),
      profile.bio or "(none)"
    )
    local new_bio = mixhive["llm.call"](bio_prompt, "sonnet"):await()
    table.insert(suggestions, suggestion(
      "bio_rewrite",
      { current = profile.bio, proposed = new_bio },
      0.85,
      "Bio score " .. tostring(score.bio) .. "/100 — too short or generic",
      true
    ))
    table.insert(tasks, task("Review and update your bio", "high"))
  end

  -- Avatar
  if not profile.avatar_url then
    table.insert(suggestions, suggestion(
      "missing_avatar",
      { action = "upload_avatar" },
      1.0,
      "No avatar — promoters skip profiles without a visual identity",
      false
    ))
    table.insert(tasks, task("Upload a profile photo", "high"))
  end

  -- Mixes
  if #mixes == 0 then
    table.insert(suggestions, suggestion(
      "no_mixes",
      { action = "upload_mix" },
      1.0,
      "No published mixes — zero audio evidence of your sound",
      false
    ))
    table.insert(tasks, task("Upload your first mix", "high"))
  end

  -- Social links
  local links = profile.social_links or {}
  if not links.soundcloud and not links.mixcloud and not links.ra then
    table.insert(suggestions, suggestion(
      "missing_social_links",
      { action = "add_links", platforms = {"soundcloud", "ra", "mixcloud"} },
      0.8,
      "No streaming profile linked — promoters cannot verify your presence",
      false
    ))
  end

  -- Score notification
  if (score.overall or 0) < 70 then
    table.insert(notifications, notify(
      "Profile score: " .. tostring(score.overall) .. "/100",
      "Weakest area: " .. (score.weakest or "?") .. ". Improve it to get more bookings.",
      "in_app",
      "/profile/edit"
    ))
  end

  mh_log("done — " .. #suggestions .. " suggestions")
  return {
    status        = #suggestions > 0 and "needs_approval" or "ok",
    suggestions   = suggestions,
    tasks         = tasks,
    notifications = notifications,
  }
end
`;

export const RELEASE_STRATEGY = `
-- Release Strategy Agent
-- Plans release timing and campaign steps from recent mix cadence + open opportunities.
-- Trigger: on_demand | approval_policy: always

function run(ctx)
  mh_log("release_strategy start", ctx.profile_id)

  local profile = mixhive["db.read_one"]("profiles", { id = ctx.profile_id }):await()
  if not profile then
    return { status = "error", message = "profile not found",
             suggestions = {}, tasks = {}, notifications = {} }
  end

  local mixes = mixhive["db.read"]("mixes", { dj_id = ctx.profile_id }, 5):await()

  -- Gather relevant open opportunities as release context
  local opps = mixhive["db.read"]("opportunities", { is_active = true }, 20):await()
  local opp_lines = {}
  for _, o in ipairs(opps) do
    local t = o.opp_type or ""
    if t == "festival" or t == "radio" or t == "contest" then
      table.insert(opp_lines, string.format("- %s (%s) deadline: %s",
        o.title or "?", t, o.deadline or "open"))
    end
  end

  local mix_lines = {}
  for _, m in ipairs(mixes) do
    table.insert(mix_lines, string.format("- %s | plays: %d | tags: %s",
      m.title or "untitled",
      m.play_count or 0,
      table.concat(m.tags or {}, ", ")))
  end

  local plan_prompt = string.format([[
You are a music release strategist for underground electronic music.
Plan a release campaign for this DJ/producer.

Profile: %s | Location: %s | Genres: %s

Recent mixes:
%s

Relevant open opportunities:
%s

Return JSON only:
{
  "release_week": "YYYY-WW or 'immediate'",
  "platforms": ["string"],
  "promo_steps": ["string", "string", "string"],
  "headline_hook": "one sentence pitch",
  "optimal_day": "Monday–Sunday"
}
]],
    profile.display_name or profile.username or "Artist",
    profile.location or "Belgium",
    table.concat(profile.genres or {}, ", "),
    #mix_lines > 0 and table.concat(mix_lines, "\\n") or "No mixes yet",
    #opp_lines > 0 and table.concat(opp_lines, "\\n") or "No open opportunities found"
  )

  local plan = mixhive["llm.json"](plan_prompt,
    '{"release_week":string,"platforms":[string],"promo_steps":[string],"headline_hook":string,"optimal_day":string}',
    "haiku"
  ):await()

  mh_log("release plan generated")

  local suggs = {
    suggestion(
      "release_plan",
      plan,
      0.80,
      "Release timing and campaign steps derived from your mix cadence and open call deadlines",
      true
    )
  }

  local tsks = {
    task("Submit mix to platforms: " .. table.concat(plan.platforms or {"Soundcloud","Bandcamp"}, ", "), "high"),
    task("Draft promo post: " .. (plan.headline_hook or "release announcement"), "medium"),
  }

  return {
    status        = "needs_approval",
    suggestions   = suggs,
    tasks         = tsks,
    notifications = {
      notify(
        "Release strategy ready",
        "Your release plan is ready for review — optimal week: " .. (plan.release_week or "TBD"),
        "in_app",
        "/agents/inbox"
      )
    },
  }
end
`;

export const SCENE_RADAR = `
-- Scene Radar Agent
-- Weekly underground scene digest for the artist's city. Trigger: cron:daily

function run(ctx)
  mh_log("scene_radar start", ctx.profile_id)

  local profile = mixhive["db.read_one"]("profiles", { id = ctx.profile_id }):await()
  local city    = (profile and profile.location) or "Brussels"

  -- Use recent mixes from that city as trend signal
  local recent_mixes = mixhive["db.read"]("mixes", { published = true }, 50):await()

  local genre_counts = {}
  for _, m in ipairs(recent_mixes) do
    local tags = m.tags or {}
    for _, tag in ipairs(tags) do
      genre_counts[tag] = (genre_counts[tag] or 0) + 1
    end
  end

  local trend_lines = {}
  for genre, count in pairs(genre_counts) do
    table.insert(trend_lines, genre .. ": " .. count)
  end
  table.sort(trend_lines, function(a, b) return a > b end)

  if #trend_lines == 0 then
    return { status = "ok", suggestions = {}, tasks = {}, notifications = {} }
  end

  local digest_prompt = string.format([[
Write a 2-paragraph underground music scene digest based on these genre play signals.
Format: insider tone, casual, no hype. Include what is rising, one actionable tip for a DJ.
Max 150 words.

Signals:
%s
]],
    table.concat(trend_lines, "\\n"):sub(1, 600)
  )

  local digest = mixhive["llm.call"](digest_prompt, "sonnet"):await()

  mh_log("digest generated")
  return {
    status = "ok",
    suggestions = {
      suggestion(
        "scene_digest",
        { city = city, digest = digest },
        0.75,
        "Weekly platform-wide underground scene intelligence",
        false
      )
    },
    tasks = {},
    notifications = {
      notify(
        "Scene update",
        digest:sub(1, 100) .. "...",
        "in_app",
        "/dashboard"
      )
    },
  }
end
`;

export const TREND_INTELLIGENCE = `
-- Trend Intelligence Agent
-- Builds aggregate underground trend reports from mix scores and audio features.
-- Trigger: cron:weekly | approval_policy: auto

function run(ctx)
  mh_log("trend_intelligence start", ctx.profile_id)

  -- Top mixes by score
  local top_mixes = mixhive["db.read"]("mixes", { published = true }, 100):await()

  if #top_mixes == 0 then
    return { status = "ok", suggestions = {}, tasks = {}, notifications = {} }
  end

  -- Aggregate tags
  local tag_counts = {}
  local genre_counts = {}
  for _, m in ipairs(top_mixes) do
    for _, t in ipairs(m.tags or {}) do
      tag_counts[t] = (tag_counts[t] or 0) + 1
    end
    for _, g in ipairs(m.genres or {}) do
      genre_counts[g] = (genre_counts[g] or 0) + 1
    end
  end

  -- Top 10 tags
  local tag_lines = {}
  for tag, count in pairs(tag_counts) do
    table.insert(tag_lines, { tag = tag, count = count })
  end
  table.sort(tag_lines, function(a, b) return a.count > b.count end)
  local top_tags = {}
  for i, t in ipairs(tag_lines) do
    if i > 10 then break end
    table.insert(top_tags, t.tag .. "(" .. t.count .. ")")
  end

  -- Top genres
  local genre_lines = {}
  for genre, count in pairs(genre_counts) do
    table.insert(genre_lines, { genre = genre, count = count })
  end
  table.sort(genre_lines, function(a, b) return a.count > b.count end)
  local top_genres = {}
  for i, g in ipairs(genre_lines) do
    if i > 8 then break end
    table.insert(top_genres, g.genre .. "(" .. g.count .. ")")
  end

  -- Audio features sample
  local audio_lines = {}
  local features = mixhive["db.read"]("audio_features", {}, 50):await()
  local bpm_sum, bpm_count = 0, 0
  local energy_sum, energy_count = 0, 0
  for _, f in ipairs(features) do
    if f.bpm and f.bpm > 0 then
      bpm_sum   = bpm_sum + f.bpm
      bpm_count = bpm_count + 1
    end
    if f.energy then
      energy_sum   = energy_sum + f.energy
      energy_count = energy_count + 1
    end
  end
  local avg_bpm    = bpm_count    > 0 and math.floor(bpm_sum / bpm_count)       or nil
  local avg_energy = energy_count > 0 and string.format("%.2f", energy_sum / energy_count) or nil

  local trend_prompt = string.format([[
Write a 3-paragraph underground electronic music trend report for Belgium/Western Europe.
Insider tone — as if written for a RA or Resident Advisor news post. No hype, no fluff.
Cover: what's rising, what's fading, one actionable tip for DJs this month.

Platform signals (%d mixes analysed):
Top tags: %s
Top genres: %s
%s
%s
]],
    #top_mixes,
    table.concat(top_tags, ", "):sub(1, 300),
    table.concat(top_genres, ", "):sub(1, 200),
    avg_bpm    and ("Avg BPM: " .. avg_bpm)    or "",
    avg_energy and ("Avg energy: " .. avg_energy) or ""
  )

  local report = mixhive["llm.call"](trend_prompt, "sonnet"):await()

  mh_log("trend_intelligence report generated")

  local payload = {
    report        = report,
    top_tags      = top_tags,
    top_genres    = top_genres,
    mix_count     = #top_mixes,
    avg_bpm       = avg_bpm,
    avg_energy    = avg_energy,
  }

  -- Upsert so repeated runs replace stale reports
  mixhive["db.upsert"]("ai_suggestions", {
    owner_id        = ctx.profile_id,
    suggestion_type = "trend_report",
    payload         = payload,
    rationale       = "Weekly aggregate from " .. #top_mixes .. " platform mixes",
    confidence      = 0.80,
    status          = "pending",
    source          = "agent",
    model           = "sonnet",
    created_at      = os.date("!%Y-%m-%dT%H:%M:%SZ"),
    updated_at      = os.date("!%Y-%m-%dT%H:%M:%SZ"),
  }):await()

  return {
    status = "ok",
    suggestions = {
      suggestion(
        "trend_report",
        payload,
        0.80,
        "Weekly aggregate from " .. #top_mixes .. " platform mixes",
        false
      )
    },
    tasks = {},
    notifications = {
      notify(
        "Weekly trend report",
        report:sub(1, 100) .. "...",
        "in_app",
        "/agents/inbox"
      )
    },
  }
end
`;

export const VENUE_FIT = `
-- Venue Fit Agent
-- Scores artist-venue compatibility using find_candidate_venues RPC +
-- active opportunity matching. The RPC gives us the venues table directly,
-- filtered by genre overlap and city. Opportunities are then intersected.
-- Trigger: on_demand | approval_policy: auto (pro tier)

function run(ctx)
  mh_log("venue_fit start", ctx.profile_id)

  local profile = mixhive["db.read_one"]("profiles", { id = ctx.profile_id }):await()
  if not profile then
    return { status = "error", message = "profile not found",
             suggestions = {}, tasks = {}, notifications = {} }
  end

  -- Use find_candidate_venues RPC for genre+city filtered venue candidates
  local city = (profile.location or ""):match("^([^,]+)") or nil
  local venues = mixhive["db.rpc"]("find_candidate_venues", {
    p_genres  = profile.genres or {},
    p_city    = city,
    p_country = "BE",
    p_limit   = 20,
  }):await()

  -- Also pull active booking opportunities to cross-reference
  local opps = mixhive["db.read"]("opportunities", { is_active = true }, 30):await()
  local booking_opps = {}
  for _, o in ipairs(opps) do
    local t = o.opp_type or ""
    if t == "gig" or t == "festival" or t == "residency" then
      table.insert(booking_opps, o)
    end
  end

  if #venues == 0 and #booking_opps == 0 then
    mh_log("no venues or booking opportunities found")
    return { status = "ok", suggestions = {}, tasks = {}, notifications = {} }
  end

  -- Build context lines for LLM scoring
  local venue_lines = {}
  for i, v in ipairs(venues) do
    if i > 15 then break end
    table.insert(venue_lines, string.format(
      "V%d. %s | %s | genres: %s | overlap: %d | capacity: %s",
      i, v.name or "?", v.city or "?",
      table.concat(v.genres or {}, ","),
      v.genre_overlap or 0,
      tostring(v.capacity or "?")
    ))
  end

  local opp_lines = {}
  for i, o in ipairs(booking_opps) do
    if i > 10 then break end
    table.insert(opp_lines, string.format(
      "O%d. [%s] %s | city: %s | comp: %s | deadline: %s",
      i, o.opp_type or "gig",
      o.title or "?",
      o.city or o.location or "?",
      o.compensation or "?",
      o.deadline or "open"
    ))
  end

  local score_prompt = string.format([[
You are a DJ booking consultant scoring venue/opportunity fit for an underground electronic artist.
Score based on: genre overlap (most important), city proximity, career stage, and compensation.

Artist: %s | Location: %s | Genres: %s | Style: %s

Candidate Venues (from DB):
%s

Active Opportunities:
%s

Return top 5 combined fits. JSON only:
{"top_5":[{"ref":"V1 or O2","name":"string","fit_score":0-100,"genre_match":"string","recommendation":"1 sentence"}]}
fit_score: 0-100.
]],
    profile.display_name or profile.username or "Artist",
    profile.location or "Belgium",
    table.concat(profile.genres or {}, ", "),
    profile.dj_style or "DJ",
    #venue_lines > 0 and table.concat(venue_lines, "\\n") or "(none)",
    #opp_lines > 0 and table.concat(opp_lines, "\\n") or "(none)"
  )

  local ranked = mixhive["llm.json"](score_prompt,
    '{"top_5":[{"ref":string,"name":string,"fit_score":number,"genre_match":string,"recommendation":string}]}',
    "haiku"
  ):await()

  local suggs = {}
  for _, hit in ipairs(ranked.top_5 or {}) do
    table.insert(suggs, suggestion(
      "venue_fit_score",
      {
        ref            = hit.ref,
        name           = hit.name,
        fit_score      = hit.fit_score,
        genre_match    = hit.genre_match,
        recommendation = hit.recommendation,
      },
      (hit.fit_score or 50) / 100,
      hit.recommendation or "Genre and location alignment detected",
      false
    ))
  end

  mh_log("venue_fit scored " .. #suggs .. " targets")

  return {
    status        = "ok",
    suggestions   = suggs,
    tasks         = {},
    notifications = #suggs > 0 and {
      notify(
        "Venue fit analysis complete",
        #suggs .. " venues/opportunities scored — top match: " .. (suggs[1] and suggs[1].payload.name or "?"),
        "in_app",
        "/agents/inbox"
      )
    } or {},
  }
end
`;

export const VISUAL_IDENTITY = `
-- Visual Identity Agent
-- Generates a coherent visual identity brief from profile and press kit data.
-- Trigger: on_demand | approval_policy: always (pro tier)

function run(ctx)
  mh_log("visual_identity start", ctx.profile_id)

  local profile = mixhive["db.read_one"]("profiles", { id = ctx.profile_id }):await()
  if not profile then
    return { status = "error", message = "profile not found",
             suggestions = {}, tasks = {}, notifications = {} }
  end

  -- Check for existing press kit
  local press_kit = mixhive["db.read_one"]("press_kits", { owner_id = ctx.profile_id }):await()
  local pk_context = ""
  if press_kit then
    local payload = press_kit.payload or {}
    pk_context = string.format("Existing press kit: tagline=%s, key_tracks=%s",
      payload.tagline or "none",
      table.concat(payload.key_tracks or {}, ", "))
  end

  local brief_prompt = string.format([[
You are a creative director specialising in underground electronic music visual identities.
Create a precise, actionable visual identity brief. No generic advice — be specific and atmospheric.

Artist: %s
Location: %s
Genres: %s
DJ Style: %s
Bio: %s
%s

Return JSON only:
{
  "color_palette": ["#hex1", "#hex2", "#hex3"],
  "palette_mood": "string",
  "typography_direction": "string",
  "reference_artists": ["string", "string"],
  "shoot_concept": "string",
  "social_grid_direction": "string",
  "logo_style": "string",
  "avoid": "string"
}
All fields required. shoot_concept max 2 sentences. Be specific about era, texture, references.
]],
    profile.display_name or profile.username or "Artist",
    profile.location or "Belgium",
    table.concat(profile.genres or {}, ", "),
    profile.dj_style or "DJ/Producer",
    (profile.bio or "No bio provided"):sub(1, 300),
    pk_context
  )

  local brief = mixhive["llm.json"](brief_prompt,
    '{"color_palette":[string],"palette_mood":string,"typography_direction":string,"reference_artists":[string],"shoot_concept":string,"social_grid_direction":string,"logo_style":string,"avoid":string}',
    "sonnet"
  ):await()

  mh_log("visual_identity brief generated")

  return {
    status = "needs_approval",
    suggestions = {
      suggestion(
        "visual_brief",
        brief,
        0.85,
        "Visual identity derived from genre, style, and bio signals",
        true
      )
    },
    tasks = {
      task("Share visual brief with designer or photographer", "medium"),
    },
    notifications = {
      notify(
        "Visual identity brief ready",
        "Your visual direction is ready for review — palette: " .. table.concat(brief.color_palette or {"?"}, ", "),
        "in_app",
        "/agents/inbox"
      )
    },
  }
end
`;
