import { Document, Page, Text, View, StyleSheet, Link, Image } from '@react-pdf/renderer';
import { colors } from '../../styles/tokens';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 11, color: '#1a1a1a' },
  header: { fontSize: 24, fontWeight: 'bold', marginBottom: 8 },
  subheader: { fontSize: 14, color: colors.text.faintest, marginBottom: 16 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 13, fontWeight: 'bold', marginBottom: 6, textTransform: 'uppercase' },
  mix: { marginBottom: 8 },
  mixTitle: { fontWeight: 'bold' },
  footer: { marginTop: 24, fontSize: 11, color: '#777' },
});

interface Mix {
  title: string;
  play_count: number;
  like_count: number;
  url_path: string;
}

interface CustomSection {
  heading: string;
  body: string;
}

interface Props {
  title: string;
  artistName: string;
  location?: string | null;
  bio?: string | null;
  genres: string[];
  website?: string | null;
  topMixes: Mix[];
  bookingPitch: string;
  technicalNotes: string[];
  avatarUrl?: string | null;
  customSections?: CustomSection[];
}

export function EpkPdfDocument({
  title,
  artistName,
  location,
  bio,
  genres,
  website,
  topMixes,
  bookingPitch,
  technicalNotes,
  avatarUrl,
  customSections,
}: Props) {
  return (
    <Document title={title} author={artistName}>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>{artistName}</Text>
        <Text style={styles.subheader}>
          {location ? `${location} · ` : ''}
          {genres.join(', ') || 'DJ / Producer'}
        </Text>

        {avatarUrl && (
          <View style={styles.section}>
            <Image src={avatarUrl} style={{ width: 120, height: 120, borderRadius: 999 }} />
          </View>
        )}

        {bio && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Bio</Text>
            <Text>{bio}</Text>
          </View>
        )}

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Booking Pitch</Text>
          <Text>{bookingPitch}</Text>
        </View>

        {topMixes.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Top Mixes</Text>
            {topMixes.map((mix, i) => (
              <View key={i} style={styles.mix}>
                <Text style={styles.mixTitle}>{mix.title}</Text>
                <Text>
                  {mix.play_count} plays · {mix.like_count} likes
                </Text>
                {mix.url_path && <Link src={`https://mixhive.app${mix.url_path}`}>Listen</Link>}
              </View>
            ))}
          </View>
        )}

        {technicalNotes.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Technical</Text>
            {technicalNotes.map((note, i) => (
              <Text key={i}>• {note}</Text>
            ))}
          </View>
        )}

        {customSections &&
          customSections.length > 0 &&
          customSections.map((section, i) => (
            <View style={styles.section} key={i}>
              <Text style={styles.sectionTitle}>{section.heading}</Text>
              <Text>{section.body}</Text>
            </View>
          ))}

        {website && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Links</Text>
            <Link src={website}>{website}</Link>
          </View>
        )}

        <Text style={styles.footer}>Generated by MixHive · mixhive.app</Text>
      </Page>
    </Document>
  );
}
