-- Migration 028: AI suggestions, feedback, and creator tasks.
--
-- The AI infrastructure layer stores every suggestion the platform generates
-- before it can affect user-facing data. Users can apply, reject, edit, and
-- rate every suggestion. Nothing is applied automatically.
--
-- ai_suggestions — structured outputs from GPT/Claude/rule-based agents.
-- ai_feedback    — user ratings and outcome tracking for every suggestion.
-- creator_tasks  — actionable to-do items generated by agents or rules.
--
-- All tables are RLS-protected to owner_id = auth.uid().
--
-- Resolves: Phase 1 AI foundation

begin;

-- ── ai_suggestions ────────────────────────────────────────────────────────────
create table if not exists ai_suggestions (
  id              uuid        primary key default gen_random_uuid(),
  owner_id        uuid        not null references profiles(id) on delete cascade,
  suggestion_type text        not null,
  payload         jsonb       not null default '{}',
  rationale       text,
  confidence      numeric(4,3) check (confidence is null or (confidence >= 0 and confidence <= 1)),
  status          text        not null default 'pending'
                              check (status in ('pending','applied','rejected','edited')),
  source          text        not null default 'gpt'
                              check (source in ('gpt','claude','rule')),
  model           text,
  version         int         not null default 1,
  applied_at      timestamptz,
  rejected_at     timestamptz,
  created_at      timestamptz not null default now()
);

create index if not exists ai_suggestions_owner_status
  on ai_suggestions (owner_id, status, created_at desc);

alter table ai_suggestions enable row level security;

drop policy if exists "ai_suggestions_owner_all" on ai_suggestions;
create policy "ai_suggestions_owner_all" on ai_suggestions
  for all
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

-- ── ai_feedback ───────────────────────────────────────────────────────────────
create table if not exists ai_feedback (
  id            uuid        primary key default gen_random_uuid(),
  suggestion_id uuid        not null references ai_suggestions(id) on delete cascade,
  owner_id      uuid        not null references profiles(id) on delete cascade,
  rating        smallint    check (rating between 1 and 5),
  comment       text,
  outcome       text        check (outcome in ('used','modified','ignored')),
  created_at    timestamptz not null default now()
);

create index if not exists ai_feedback_suggestion on ai_feedback (suggestion_id);
create index if not exists ai_feedback_owner     on ai_feedback (owner_id);

alter table ai_feedback enable row level security;

drop policy if exists "ai_feedback_owner_all" on ai_feedback;
create policy "ai_feedback_owner_all" on ai_feedback
  for all
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

-- ── creator_tasks ─────────────────────────────────────────────────────────────
create table if not exists creator_tasks (
  id                  uuid        primary key default gen_random_uuid(),
  owner_id            uuid        not null references profiles(id) on delete cascade,
  task_type           text        not null,
  title               text        not null check (char_length(title) <= 300),
  priority            smallint    not null default 2 check (priority between 1 and 5),
  due_date            date,
  linked_entity_type  text,
  linked_entity_id    uuid,
  status              text        not null default 'open'
                                  check (status in ('open','snoozed','done')),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index if not exists creator_tasks_owner_status
  on creator_tasks (owner_id, status, priority desc, created_at desc);

alter table creator_tasks enable row level security;

drop policy if exists "creator_tasks_owner_all" on creator_tasks;
create policy "creator_tasks_owner_all" on creator_tasks
  for all
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

-- updated_at trigger
create or replace function update_creator_tasks_updated_at()
  returns trigger language plpgsql security definer set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists creator_tasks_updated_at on creator_tasks;
create trigger creator_tasks_updated_at
  before update on creator_tasks
  for each row execute function update_creator_tasks_updated_at();

commit;

-- Resolves: Phase 1 AI foundation
